lib/repo-commit: Cast variables for printf()
Because we don't know how wide %lu is, use %llu and cast our guint64s
to (long long unsigned) so we know they match.

This fixes:

src/libostree/ostree-repo-commit.c: In function 'write_content_object':
src/libostree/ostree-repo-commit.c:906:62: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'guint64' {aka 'long long unsigned int'} [-Werror=format=]
       return glnx_throw (error, "min-free-space-size %luMB would be exceeded, %s more required",
                                                      ~~^
                                                      %llu
                          self->min_free_space_mb, formatted_required);

Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>